<?php

/**
 * @file
 * Add regions to SOE
 */

/**
 * Implements hook_define_region().
 */
function stanford_soe_regions_define_regions() {
  $region['full_width_super_hero'] = array(
    'title' => 'Full Width Super Hero',
    'js' => drupal_get_path('module', 'stanford_soe_regions') . '/js/stanford_soe_regions.js',
    'css' => drupal_get_path('module', 'stanford_soe_regions') . '/css/stanford_soe_regions.css',
    'render_callback' => '_full_width_super_hero_render_region',
  );
  return $region;
}

/**
 * Helper function for rendering the blocks in this region
 */
function _full_width_super_hero_render_region($block_html, $block) {
  $renderable_block = _block_get_renderable_array(array($block));
  $output = drupal_render($renderable_block);
  return $output;
}

/**
 * Implements hook_page_alter().
 */
function stanford_soe_regions_page_alter(&$page) {
  //TODO: Add logic to this if statement to only add region when needed.
  if (!path_is_admin(current_path())) {
    //Moving location where regions_module is appended.
    $regions_module = $page['page_bottom']['regions_module'];
    $page['admin_shortcuts']['regions_module'] = $regions_module;
  }
  unset($page['page_bottom']['regions_module']);
}
